package com.thena3ik.weatherbot.commands;

import com.thena3ik.weatherbot.JsonFileManager;
import com.thena3ik.weatherbot.image.ImageConstructor;
import net.dv8tion.jda.api.events.guild.GuildReadyEvent;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.interactions.commands.OptionMapping;
import net.dv8tion.jda.api.interactions.commands.OptionType;
import net.dv8tion.jda.api.interactions.commands.build.CommandData;
import net.dv8tion.jda.api.interactions.commands.build.Commands;
import net.dv8tion.jda.api.interactions.commands.build.OptionData;
import net.dv8tion.jda.api.utils.FileUpload;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.function.UnaryOperator;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class CommandManager extends ListenerAdapter {

    private static final JsonFileManager manager = new JsonFileManager();

    /**
     * Handles slash command interactions from users.
     * This method listens for slash command events and executes corresponding logic based on the command name.
     *
     * @param event The SlashCommandInteractionEvent representing the user interaction with a slash command.
     */
    @Override
    public void onSlashCommandInteraction(SlashCommandInteractionEvent event) {
        String command = event.getName();

        switch (command) {
            case "ping" -> {
                // Respond to the "ping" command with "Pong!" as an ephemeral message (visible only to the user).
                event.deferReply().setEphemeral(true).queue();
                event.getHook().sendMessage("Pong!").queue();
            }
            case "weather" -> {

                // Handles the weather command.
                long serverId = Objects.requireNonNull(event.getGuild()).getIdLong();

                // First, retrieves the "city" option value specified by the user.
                OptionMapping cityOption = event.getOption("city");
                String cityRaw;
                String city = "";

                if (cityOption != null) {
                    cityRaw = cityOption.getAsString();

                    // Capitalize the first letter and make the rest lowercase for better presentation.

                    String keySymbol = " ";
                    if (cityRaw.contains("-")) keySymbol = "-";

                    UnaryOperator<String> capitalize = str ->
                            str.substring(0, 1).toUpperCase() + str.substring(1).toLowerCase();
                    city = Stream.of(cityRaw.split(keySymbol)).map(capitalize).collect(Collectors.joining(keySymbol));
                }

                // Acknowledge the interaction to let the user know the bot is processing the request.
                event.deferReply().queue();

                try {
                    // Construct the weather message with city name, image, and a button to change the image theme.
                    ImageConstructor img = new ImageConstructor(city, manager.getTheme(serverId));
                    //img.saveImage();

                    event.getHook().sendMessage("This is the weather in " + city + "!")
                            .addFiles(FileUpload.fromData(img.getAsFile())) // Attach image generated by ImageConstructor
                            .queue();

                    // Catch any exceptions that might occur during weather processing and send an ephemeral error message.
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                    event.getHook().sendMessage("An error occurred while processing your request.")
                            .setEphemeral(true)
                            .queue();
                }
            }
            case "theme" -> {
                OptionMapping themeOption = event.getOption("theme");

                long serverId = Objects.requireNonNull(event.getGuild()).getIdLong();
                String theme = manager.getTheme(serverId);

                if (themeOption != null) {
                    theme = themeOption.getAsString();
                    manager.saveTheme(serverId, theme);
                }

                // Acknowledge the interaction to let the user know the bot is processing the request.
                event.deferReply().queue();
                try {
                    event.getHook().sendMessage(Objects.requireNonNull(theme).substring(0,1).toUpperCase() + theme.substring(1).toLowerCase()
                            + " theme is successfully applied!").queue();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                    event.getHook().sendMessage("An error occurred while processing your request.")
                            .setEphemeral(true)
                            .queue();
                }
            }
        }
    }

    @Override
    public void onGuildReady(GuildReadyEvent event) {
        List<CommandData> commandData = new ArrayList<>();
        commandData.add(Commands.slash("ping", "Default ping-pong game :)"));

        // Command: /weather: <city> <date>
        OptionData providedCity = new OptionData(OptionType.STRING, "city",
                "City where you want to check the weather", true);
        commandData.add(Commands.slash("weather", "Shows an actual weather")
                .addOptions(providedCity));

        // Command: /theme: <theme>
        OptionData themes = new OptionData(OptionType.STRING, "theme", "!!!")
                .addChoice("Black", "black")
                .addChoice("White", "white")
                .addChoice("Season", "season");
        commandData.add(Commands.slash("theme", "Changes the theme")
                .addOptions(themes));

        event.getGuild().updateCommands().addCommands(commandData).queue();
    }
}
